name: gems_tarifi
description: Gems Tarifi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.1.0
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.3.8
  provider: ^6.0.5
  flutter_material_color_picker: ^1.2.0
  hive_flutter: ^2.0.0-dev
  wakelock_plus: ^1.1.1
  smooth_page_indicator: ^1.1.0
  html: ^0.15.4
  screenshot: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa_reqular.ttf
