name: gems_tarifi
description: Gems Tarifi

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.11
  sqflite: ^2.0.3
  flutter_html: ^2.2.1
  share_plus: ^4.0.10
  clipboard: ^0.1.3
  scrollable_positioned_list: ^0.3.2
  provider: ^6.0.3
  url_launcher: ^6.1.5
  o_color_picker: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  screenshot: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/databases/
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf